"""阶段11: 把 run_all 的结果生成为可交互 Cursor Canvas(.canvas.tsx)。

Canvas 是 Cursor 里可并排打开的实时 React 面板。本脚本读取
artifacts/run_all_summary.json, 把数据**内联**进单文件 canvas 模板并写到
Cursor 托管的 canvases 目录, 从而得到一个数据驱动、可刷新的交互面板:
- 币种切换(BTC/ETH)、指标切换(AUC/准确率/Brier)、双币净值对比开关;
- 专家 vs 集成判别力对比图、含成本回测 KPI、OOF 净值曲线、专家指标表。

刷新: 重新跑 scripts/10_run_all.py 后再跑本脚本即可更新面板数据。

用法:
    python scripts/10_run_all.py
    python scripts/11_make_canvas.py            # 写到默认 canvases 目录
    python scripts/11_make_canvas.py --out "D:/path/to/xxx.canvas.tsx"
"""
import argparse
import json
from pathlib import Path

import _bootstrap  # noqa: F401

from crypto_alpha.config import Config

_TEMPLATE = r'''import {
  BarChart, LineChart, Card, CardHeader, CardBody, Grid, Row, Stack, H1, H2,
  Text, Stat, Pill, Select, Toggle, Table, Callout, Divider, Spacer,
  useCanvasState,
} from "cursor/canvas";

type Report = { n: number; auc: number; brier: number; logloss: number; accuracy: number; base_rate: number };
type Backtest = { n_events: number; n_trades: number; total_return: number; sharpe: number; max_drawdown: number; win_rate: number; avg_pnl: number; calmar: number };
type Decision = { signal: string; win_probability: number; entry_price: number; stop_loss: number; take_profit: number; suggested_position_pct: number; atr: number; symbol: string; timestamp: string };
type EquityCurve = { dates: string[]; values: number[] };
type SymbolData = {
  n_events: number; pos_rate: number; date_start: string; date_end: string;
  ensemble_report: Report; expert_reports: Record<string, Report>;
  backtest: Backtest; decision: Decision; equity_curve: EquityCurve;
};
type Meta = { generated_at: string; experts_requested: string[]; experts_run: string[]; experts_skipped: Record<string, string>; seed: number; data_mode: string; news_mode: string; do_cpcv: boolean };
type Summary = { meta: Meta; symbols: Record<string, SymbolData> };

const DATA: Summary = __DATA__;

const pct = (x: number) => `${(x * 100).toFixed(2)}%`;
const f3 = (x: number) => x.toFixed(3);
// dashboard generated by scripts/11_make_canvas.py
const short = (s: string) => s.slice(0, 16);

const METRIC_OPTIONS = [
  { value: "auc", label: "AUC(判别力)" },
  { value: "accuracy", label: "准确率" },
  { value: "brier", label: "Brier(越低越好)" },
];

export default function CryptoAlphaDashboard() {
  const symbols = Object.keys(DATA.symbols);
  const [symbol, setSymbol] = useCanvasState<string>("symbol", symbols[0] ?? "");
  const [metric, setMetric] = useCanvasState<string>("metric", "auc");
  const [compareBoth, setCompareBoth] = useCanvasState<boolean>("compareBoth", false);

  const d = DATA.symbols[symbol] ?? DATA.symbols[symbols[0]];
  const meta = DATA.meta;
  const dec = d.decision;
  const bt = d.backtest;
  const expertNames = Object.keys(d.expert_reports);
  const configs = [...expertNames, "ensemble"];

  const metricVal = (name: string): number => {
    const r = name === "ensemble" ? d.ensemble_report : d.expert_reports[name];
    return (r as unknown as Record<string, number>)[metric];
  };
  const barData = configs.map(metricVal);
  const refLine = metric === "brier"
    ? { value: d.ensemble_report.base_rate * (1 - d.ensemble_report.base_rate), label: "基线", tone: "warning" as const }
    : { value: 0.5, label: "随机=0.5", tone: "warning" as const };

  const sigTone = dec.signal === "LONG" ? "success" : dec.signal === "SHORT" ? "danger" : undefined;

  // 净值曲线(可叠加另一币种, 按索引对齐并截到公共长度)
  const shown = compareBoth ? symbols : [symbol];
  const minLen = Math.min(...shown.map((s) => DATA.symbols[s].equity_curve.values.length));
  const cats = d.equity_curve.dates.slice(0, minLen);
  const eqSeries = shown.map((s) => ({
    name: s,
    data: DATA.symbols[s].equity_curve.values.slice(0, minLen),
    tone: (s === symbol ? "info" : "neutral") as "info" | "neutral",
  }));

  const bestAuc = Math.max(...configs.map((c) => (c === "ensemble" ? d.ensemble_report.auc : d.expert_reports[c].auc)));

  return (
    <Stack gap={18} style={{ padding: 20, maxWidth: 1080, margin: "0 auto" }}>
      <Stack gap={4}>
        <H1>Crypto-Alpha · 多专家交易信号面板</H1>
        <Text tone="secondary" size="small">
          来源: run_all_summary.json · 生成(UTC) {meta.generated_at} · 数据 {meta.data_mode} · 新闻 {meta.news_mode} · seed {meta.seed} · CPCV {meta.do_cpcv ? "开" : "关"}
        </Text>
      </Stack>

      <Row gap={8} align="center" wrap>
        {symbols.map((s) => (
          <span key={s}><Pill active={s === symbol} onClick={() => setSymbol(s)}>{s}</Pill></span>
        ))}
        <Spacer />
        {meta.experts_run.map((e) => (
          <span key={e}><Pill active size="sm">{`✓ ${e}`}</Pill></span>
        ))}
        {Object.keys(meta.experts_skipped).map((e) => (
          <span key={e}><Pill size="sm" title={meta.experts_skipped[e]}>{`⤫ ${e}`}</Pill></span>
        ))}
      </Row>

      <Row gap={16} align="stretch" style={{ flexWrap: "wrap" }}>
        <Card style={{ minWidth: 260, flex: "1 1 260px" }}>
          <CardHeader trailing={short(dec.timestamp)}>最新决策 · {symbol}</CardHeader>
          <CardBody>
            <Row gap={20} align="center" wrap>
              <Stat value={dec.signal} label="信号" tone={sigTone} />
              <Stat value={pct(dec.win_probability)} label="胜率概率" />
              <Stat value={pct(dec.suggested_position_pct)} label="建议仓位" />
            </Row>
            <Divider style={{ margin: "12px 0" }} />
            <Grid columns={3} gap={12}>
              <Stat value={dec.entry_price} label="入场价" />
              <Stat value={dec.stop_loss} label="止损" tone="danger" />
              <Stat value={dec.take_profit} label="止盈" tone="success" />
            </Grid>
          </CardBody>
        </Card>

        <Card style={{ minWidth: 260, flex: "1 1 320px" }}>
          <CardHeader trailing={`${d.n_events} 样本`}>无泄漏 OOF 回测</CardHeader>
          <CardBody>
            <Grid columns={3} gap={12}>
              <Stat value={f3(bt.sharpe)} label="Sharpe" tone={bt.sharpe >= 0 ? "success" : "danger"} />
              <Stat value={pct(bt.total_return)} label="总收益" tone={bt.total_return >= 0 ? "success" : "danger"} />
              <Stat value={pct(bt.max_drawdown)} label="最大回撤" tone="danger" />
              <Stat value={pct(bt.win_rate)} label="胜率" />
              <Stat value={f3(bt.calmar)} label="Calmar" tone={bt.calmar >= 0 ? "success" : "danger"} />
              <Stat value={bt.n_trades} label="交易数" />
            </Grid>
          </CardBody>
        </Card>
      </Row>

      <Stack gap={8}>
        <Row align="center" gap={12}>
          <H2 style={{ margin: 0 }}>专家 vs 集成 · 判别力对比</H2>
          <Spacer />
          <Text tone="secondary" size="small">指标</Text>
          <div style={{ width: 190 }}>
            <Select value={metric} onChange={setMetric} options={METRIC_OPTIONS} />
          </div>
        </Row>
        <BarChart
          categories={configs}
          series={[{ name: METRIC_OPTIONS.find((m) => m.value === metric)?.label ?? metric, data: barData }]}
          height={230}
          beginAtZero={false}
          referenceLines={[refLine]}
          showValues
        />
        <Text tone="tertiary" size="small">
          {symbol} · {short(d.date_start)} ~ {short(d.date_end)} · 集成对 AUC 通常高于任一单专家(Stacking 增益)。指标基于 Purged CV 的样本外 OOF 概率。
        </Text>
      </Stack>

      <Stack gap={8}>
        <Row align="center" gap={12}>
          <H2 style={{ margin: 0 }}>OOF 净值曲线</H2>
          <Spacer />
          <Text tone="secondary" size="small">对比双币</Text>
          <Toggle checked={compareBoth} onChange={setCompareBoth} />
        </Row>
        <LineChart
          categories={cats}
          series={eqSeries}
          height={260}
          beginAtZero={false}
          fill={!compareBoth}
          referenceLines={[{ value: 1.0, label: "本金", tone: "neutral" }]}
        />
        <Text tone="tertiary" size="small">
          纵轴: 净值(初始=1.0) · 横轴: 日期 · 含手续费+滑点成本 · {compareBoth ? "两币按索引对齐截至公共长度" : symbol}
        </Text>
      </Stack>

      <Stack gap={8}>
        <H2 style={{ margin: 0 }}>各专家指标(OOF) · {symbol}</H2>
        <Table
          headers={["模型", "AUC", "Brier", "准确率", "样本"]}
          columnAlign={["left", "right", "right", "right", "right"]}
          rowTone={[...expertNames.map((n) => (d.expert_reports[n].auc >= bestAuc ? "success" : undefined)), "info"] as ("success" | "info" | undefined)[]}
          rows={[
            ...expertNames.map((n) => [n, f3(d.expert_reports[n].auc), f3(d.expert_reports[n].brier), pct(d.expert_reports[n].accuracy), d.expert_reports[n].n]),
            ["集成(stacking)", f3(d.ensemble_report.auc), f3(d.ensemble_report.brier), pct(d.ensemble_report.accuracy), d.ensemble_report.n],
          ]}
        />
      </Stack>

      <Callout tone="warning" title="解读须知">
        指标均基于无泄漏的样本外 OOF 概率与含成本回测。当前为{meta.data_mode}数据{meta.data_mode === "合成" ? "(接真实 OHLCV 后重跑即为真实多年回测)" : ""},
        AUC≈0.5 表示接近随机, 真实 alpha 需在 CPCV(DSR/PBO)下进一步确认。仅供研究, 非投资建议。
      </Callout>
    </Stack>
  );
}
'''


def default_out() -> Path:
    return (Path.home() / ".cursor" / "projects" / "d-desktop-cryptoCurrency"
            / "canvases" / "crypto-alpha-dashboard.canvas.tsx")


def main():
    ap = argparse.ArgumentParser(description="生成可交互 Cursor Canvas 面板")
    ap.add_argument("--out", default=None, help="canvas 输出路径(.canvas.tsx)")
    args = ap.parse_args()

    cfg = Config.load()
    summ_path = cfg.artifacts_dir / "run_all_summary.json"
    if not summ_path.exists():
        raise SystemExit("未找到 run_all_summary.json; 请先运行 scripts/10_run_all.py")
    summary = json.loads(summ_path.read_text(encoding="utf-8"))
    # 只保留 canvas 需要的字段(去掉可能存在的 base64 图)
    for s in summary.get("symbols", {}).values():
        s.pop("equity_b64", None)

    tsx = _TEMPLATE.replace("__DATA__", json.dumps(summary, ensure_ascii=False))
    out = Path(args.out) if args.out else default_out()
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(tsx, encoding="utf-8")
    print(f"[ok] Canvas -> {out}")
    print("在 Cursor 中点击该路径即可并排打开面板。刷新数据: 重跑 10_run_all 后再跑本脚本。")


if __name__ == "__main__":
    main()
